### ISSUE TITLE
Encountered error: Cannot find module 'child_process'

### ISSUE THREAD

**Issue by AkritiSondhi** [drudge/node-keychain#8]
I am trying to use the library in my project, but it shows an error when I run the application. My application is built using webpack. The error is as follows:

ERROR in ./node_modules/keychain/keychain.js
Module not found: Error: Can't resolve 'child_process' in '/Users/test/TestApp/node_modules/keychain'
 @ ./node_modules/keychain/keychain.js 11:12-36
 @ ./src/js/index.js

Any help is appreciated. Thanks in advance.

**Comment by derhuerst** [comment]
[`child_process` is a native Node.js module.](https://nodejs.org/api/child_process.html) I don't think that this package works in the browser, as AFAIK browsers don't expose an API to webpages for accessing the system keychain.

**Comment by drudge** [comment]
Correct, this package is meant to run in Node.js. It doesn't make sense for it to run in a browser because it's expecting to run on a macOS machine with access to `/usr/bin/security`.
